import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from './components/header'
import Footer from './components/footer'
import WebDev from './components/webDevelopement'
import Process from './components/process'
import Innovation from './components/innovation'
import Collaborative from './components/collaborative'
import Costing from './components/costing'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/> 

      <main className={styles.main}>
      
      
        {/* <WebDev/>
        <Innovation/>
        <Process/>
        <Collaborative/>
        <Costing/>
        <Footer/> */}
      </main>

    </div>
  )
}
